name: Compress Files

on:
  release:
    types: [published]

jobs:
  compress-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Compress Directory
        uses: somaz94/compress-decompress@v1
        with:
          command: compress
          source: ./src
          format: zip
          includeRoot: 'false'
      
      - name: Rename file 
        run: mv ./src/src.zip ./src/CreateBigCannons-ClearGlass.zip
      
      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: ./src/CreateBigCannons-ClearGlass.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
