name: Compress Files

on:
  release:
    types: [published]

jobs:
  compress-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Compress Directory
        uses: somaz94/compress-decompress@v1
        with:
          command: compress
          source: ./src
          format: zip
          includeRoot: 'false'
      
      - name: Rename file 
        run: mv ./src/src.zip ./src/CreateBigCannons-ClearGlass.zip

      - name: Upload to Release
        uses: Shopify/upload-to-release@v2.0.0
        with:
          # Artifact name
          name: CreateBigCannons-ClearGlass.zip
          # Path to the file to upload
          path: ./src/CreateBigCannons-ClearGlass.zip
          # Content type for the file
          content-type: application/zip
          repo-token: ${{ secrets.GITHUB_TOKEN }}
